/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-01-14 17:53:03 UTC)
 * on 2015-03-11 at 22:42:58 UTC 
 * Modify at your own risk.
 */

package com.blogger.programmingheroes.endpoint.chat;

/**
 * Service definition for Chat (v1).
 *
 * <p>
 * API para una aplicación de chats.
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ChatRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Chat extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the Chat library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://chat-dot-pruebas-gae.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "chat/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Chat(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Chat(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "createContact".
   *
   * This request holds the parameters needed by the chat server.  After setting any optional
   * parameters, call the {@link CreateContact#execute()} method to invoke the remote operation.
   *
   * @param name
   * @param regid
   * @return the request
   */
  public CreateContact createContact(java.lang.String name, java.lang.String regid) throws java.io.IOException {
    CreateContact result = new CreateContact(name, regid);
    initialize(result);
    return result;
  }

  public class CreateContact extends ChatRequest<com.blogger.programmingheroes.endpoint.chat.model.Contact> {

    private static final String REST_PATH = "createcontact";

    /**
     * Create a request for the method "createContact".
     *
     * This request holds the parameters needed by the the chat server.  After setting any optional
     * parameters, call the {@link CreateContact#execute()} method to invoke the remote operation. <p>
     * {@link CreateContact#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param name
     * @param regid
     * @since 1.13
     */
    protected CreateContact(java.lang.String name, java.lang.String regid) {
      super(Chat.this, "POST", REST_PATH, null, com.blogger.programmingheroes.endpoint.chat.model.Contact.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      this.regid = com.google.api.client.util.Preconditions.checkNotNull(regid, "Required parameter regid must be specified.");
    }

    @Override
    public CreateContact setAlt(java.lang.String alt) {
      return (CreateContact) super.setAlt(alt);
    }

    @Override
    public CreateContact setFields(java.lang.String fields) {
      return (CreateContact) super.setFields(fields);
    }

    @Override
    public CreateContact setKey(java.lang.String key) {
      return (CreateContact) super.setKey(key);
    }

    @Override
    public CreateContact setOauthToken(java.lang.String oauthToken) {
      return (CreateContact) super.setOauthToken(oauthToken);
    }

    @Override
    public CreateContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (CreateContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public CreateContact setQuotaUser(java.lang.String quotaUser) {
      return (CreateContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public CreateContact setUserIp(java.lang.String userIp) {
      return (CreateContact) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public CreateContact setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String regid;

    /**

     */
    public java.lang.String getRegid() {
      return regid;
    }

    public CreateContact setRegid(java.lang.String regid) {
      this.regid = regid;
      return this;
    }

    @Override
    public CreateContact set(String parameterName, Object value) {
      return (CreateContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "deleteContact".
   *
   * This request holds the parameters needed by the chat server.  After setting any optional
   * parameters, call the {@link DeleteContact#execute()} method to invoke the remote operation.
   *
   * @param name
   * @param regid
   * @return the request
   */
  public DeleteContact deleteContact(java.lang.String name, java.lang.String regid) throws java.io.IOException {
    DeleteContact result = new DeleteContact(name, regid);
    initialize(result);
    return result;
  }

  public class DeleteContact extends ChatRequest<Void> {

    private static final String REST_PATH = "deleteContact";

    /**
     * Create a request for the method "deleteContact".
     *
     * This request holds the parameters needed by the the chat server.  After setting any optional
     * parameters, call the {@link DeleteContact#execute()} method to invoke the remote operation. <p>
     * {@link DeleteContact#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientR
     * equest)} must be called to initialize this instance immediately after invoking the constructor.
     * </p>
     *
     * @param name
     * @param regid
     * @since 1.13
     */
    protected DeleteContact(java.lang.String name, java.lang.String regid) {
      super(Chat.this, "POST", REST_PATH, null, Void.class);
      this.name = com.google.api.client.util.Preconditions.checkNotNull(name, "Required parameter name must be specified.");
      this.regid = com.google.api.client.util.Preconditions.checkNotNull(regid, "Required parameter regid must be specified.");
    }

    @Override
    public DeleteContact setAlt(java.lang.String alt) {
      return (DeleteContact) super.setAlt(alt);
    }

    @Override
    public DeleteContact setFields(java.lang.String fields) {
      return (DeleteContact) super.setFields(fields);
    }

    @Override
    public DeleteContact setKey(java.lang.String key) {
      return (DeleteContact) super.setKey(key);
    }

    @Override
    public DeleteContact setOauthToken(java.lang.String oauthToken) {
      return (DeleteContact) super.setOauthToken(oauthToken);
    }

    @Override
    public DeleteContact setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (DeleteContact) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public DeleteContact setQuotaUser(java.lang.String quotaUser) {
      return (DeleteContact) super.setQuotaUser(quotaUser);
    }

    @Override
    public DeleteContact setUserIp(java.lang.String userIp) {
      return (DeleteContact) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String name;

    /**

     */
    public java.lang.String getName() {
      return name;
    }

    public DeleteContact setName(java.lang.String name) {
      this.name = name;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.String regid;

    /**

     */
    public java.lang.String getRegid() {
      return regid;
    }

    public DeleteContact setRegid(java.lang.String regid) {
      this.regid = regid;
      return this;
    }

    @Override
    public DeleteContact set(String parameterName, Object value) {
      return (DeleteContact) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getAllContacts".
   *
   * This request holds the parameters needed by the chat server.  After setting any optional
   * parameters, call the {@link GetAllContacts#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public GetAllContacts getAllContacts() throws java.io.IOException {
    GetAllContacts result = new GetAllContacts();
    initialize(result);
    return result;
  }

  public class GetAllContacts extends ChatRequest<com.blogger.programmingheroes.endpoint.chat.model.ContactCollection> {

    private static final String REST_PATH = "getallcontacts";

    /**
     * Create a request for the method "getAllContacts".
     *
     * This request holds the parameters needed by the the chat server.  After setting any optional
     * parameters, call the {@link GetAllContacts#execute()} method to invoke the remote operation.
     * <p> {@link GetAllContacts#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @since 1.13
     */
    protected GetAllContacts() {
      super(Chat.this, "GET", REST_PATH, null, com.blogger.programmingheroes.endpoint.chat.model.ContactCollection.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAllContacts setAlt(java.lang.String alt) {
      return (GetAllContacts) super.setAlt(alt);
    }

    @Override
    public GetAllContacts setFields(java.lang.String fields) {
      return (GetAllContacts) super.setFields(fields);
    }

    @Override
    public GetAllContacts setKey(java.lang.String key) {
      return (GetAllContacts) super.setKey(key);
    }

    @Override
    public GetAllContacts setOauthToken(java.lang.String oauthToken) {
      return (GetAllContacts) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAllContacts setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAllContacts) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAllContacts setQuotaUser(java.lang.String quotaUser) {
      return (GetAllContacts) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAllContacts setUserIp(java.lang.String userIp) {
      return (GetAllContacts) super.setUserIp(userIp);
    }

    @Override
    public GetAllContacts set(String parameterName, Object value) {
      return (GetAllContacts) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "sendMessage".
   *
   * This request holds the parameters needed by the chat server.  After setting any optional
   * parameters, call the {@link SendMessage#execute()} method to invoke the remote operation.
   *
   * @param message
   * @param content the {@link com.blogger.programmingheroes.endpoint.chat.model.Contact}
   * @return the request
   */
  public SendMessage sendMessage(java.lang.String message, com.blogger.programmingheroes.endpoint.chat.model.Contact content) throws java.io.IOException {
    SendMessage result = new SendMessage(message, content);
    initialize(result);
    return result;
  }

  public class SendMessage extends ChatRequest<Void> {

    private static final String REST_PATH = "sendmessage";

    /**
     * Create a request for the method "sendMessage".
     *
     * This request holds the parameters needed by the the chat server.  After setting any optional
     * parameters, call the {@link SendMessage#execute()} method to invoke the remote operation. <p>
     * {@link
     * SendMessage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param message
     * @param content the {@link com.blogger.programmingheroes.endpoint.chat.model.Contact}
     * @since 1.13
     */
    protected SendMessage(java.lang.String message, com.blogger.programmingheroes.endpoint.chat.model.Contact content) {
      super(Chat.this, "POST", REST_PATH, content, Void.class);
      this.message = com.google.api.client.util.Preconditions.checkNotNull(message, "Required parameter message must be specified.");
    }

    @Override
    public SendMessage setAlt(java.lang.String alt) {
      return (SendMessage) super.setAlt(alt);
    }

    @Override
    public SendMessage setFields(java.lang.String fields) {
      return (SendMessage) super.setFields(fields);
    }

    @Override
    public SendMessage setKey(java.lang.String key) {
      return (SendMessage) super.setKey(key);
    }

    @Override
    public SendMessage setOauthToken(java.lang.String oauthToken) {
      return (SendMessage) super.setOauthToken(oauthToken);
    }

    @Override
    public SendMessage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (SendMessage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public SendMessage setQuotaUser(java.lang.String quotaUser) {
      return (SendMessage) super.setQuotaUser(quotaUser);
    }

    @Override
    public SendMessage setUserIp(java.lang.String userIp) {
      return (SendMessage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String message;

    /**

     */
    public java.lang.String getMessage() {
      return message;
    }

    public SendMessage setMessage(java.lang.String message) {
      this.message = message;
      return this;
    }

    @Override
    public SendMessage set(String parameterName, Object value) {
      return (SendMessage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Chat}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Chat}. */
    @Override
    public Chat build() {
      return new Chat(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ChatRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setChatRequestInitializer(
        ChatRequestInitializer chatRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(chatRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
